[build]
  command = "yarn build && mkdir -p .netlify/static && cp -R node_modules/.cache/nuxt/.nuxt/dist/client/. .netlify/static && cp -R public/. .netlify/static"
  publish = ".netlify/static"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
