[build]
  command = "yarn build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[functions."sendReminder"]
  schedule = "*/1 * * * *"
